### ISSUE TITLE
Running SV-Pop

### ISSUE THREAD

**Issue by oalavijeh** [mattravenhall/SV-Pop#3]
Dear Matt, 

I was hoping to run SV-pop on a large number (>1000) VCFs called by Manta and Canvas. At present these files are merged so each person has a single VCF with all the SV-types merged into one and the types appearing in the "INFO" column e.g. MantaDEL, MantaINS etc. 

If I wanted to run SV-pop am I correct in thinking I need to separate out each call type per patient. 

I also have VCFs of each type of SV call but merged across all 1000 patients and am unsure if I can use this directly? 

Apologies for the novice questions 

All the best

Omid

**Comment by mattravenhall** [comment]
Hi oalavijeh,

Each input VCF file should consist of a single sample/patient and a single SV-type. Each run of the Analysis module should also feature only a single SV type. Note that SV types should be DUP, DEL, INS, or INV (as produced by DELLY and similar).

For the specific arguments check out the expanded help for the Analysis module at github.com/mattravenhall/SV-Pop/wiki/Analysis-Expanded-Help .

Hope that helps!

**Comment by oalavijeh** [comment]
Thanks!
