### ISSUE TITLE
Steps required to go from analysis to visualization

### ISSUE THREAD

**Issue by pietermonsieurs** [mattravenhall/SV-Pop#5]
I tried to go from the analysis part to visualization. However, this raised some issues: 

1) running the SV-pop command: 
`/software/SV-Pop/Analysis/SVPop -F=SampleFilesFilter.txt -M=DUP -R=${ref_genome_gff} --refFormat=gff --multithreads=True --threads=19 --suppressWarnings=False`
This creates a "merged" file called: Merged_DUP_chrALL_variants_annotated_v1.1.csv

2) running preprocess command:
`../software/SV-Pop/Analysis/SVPop --PREPROCESS  --variantFile=outFile`
This command looks for a duplication file called "outFile_DUP_chrALL_variants_annotated_v1.1.csv", however this does not exist, and I assume I should input here the Merged_DUP_chrALL_variants_annotated_v1.1. When creating a symbolic link: 
`ln -s Merged_DUP_chrALL_variants_annotated_v1.1.csv outFile_DUP_chrALL_variants_annotated_v1.1.csv`
I got the error message that he cannot find the windows file: outFile_DUP_chrALL_windows_annotated_v1.1.csv. However, I cannot find - like with the variants file - an equivalent file called Merged_DUP_chrALL_windows_annotated_v1.1.csv

3) create a merged windows file based on the variants file. 
Not sure whether I use this command correctly, but I could not find more details in the wiki. The help command says that it converts a Variant File into a window file. When running the command
`../software/SV-Pop/Analysis/SVPop --CONVERT --variantFile=outFile_DUP_chrALL_variants_annotated_v1.1.csv --refFile=SVPop_Files/annotation.txt` 
I get the same output as what I got before (the files with extension windows_annotated_v1.1.csv) are overwritten with the new file (which seem to be the same as before, but now containing the annotation)

4) Concatenate windows files
Next, I tried to concatenate the different files ending with windows_annotated_v1.1.csv using awk
`awk 'FNR>1' *windows_annotated_v1.1.csv > outFile_DUP_chrALL_windows_annotated_v1.1.csv`
(afterwards, add again the header). 
Afterwards running the ../software/SV-Pop/Analysis/SVPop --PREPROCESS  --variantFile=outFile command does seem to run without errors. However, when visualizing those files, I only get empty plots, and for population I can only choose between "Features" and "Samples". 
However, also adding a dummy population did not solve the issue, as this resulted in a value of 0.0 for all windows

I added the files used for visualization. 

[viz.zip](https://github.com/mattravenhall/SV-Pop/files/4911875/viz.zip)

**Comment by mattravenhall** [comment]
Hey Pieter,

I think this issue stems from SVPop not properly handling your initial command, as it should have created both merged variants and merged windows files for the input model. I've therefore improved the handling of file detection during the window merging step and made the 'files not found' warnings clearer in the logs ([commit ad4088787](https://github.com/mattravenhall/SV-Pop/commit/ad40887876e06c4c5e3d9cb11beba1e4f6ebc79a)). I've also refined the SV type checks in passing, as the previous update was filtering out some good variants.

Does updating to [version 1.2.1](https://github.com/mattravenhall/SV-Pop/releases/tag/v.1.2.1) resolve now correctly produce the merged variants and merged windows files for you?

E.g:
```bash
# Create variant files
../SVPop -F=SampleFiles.txt -M=DUP -R=PlasmoDB-46_PvivaxP01.gff
 --threads=20

# Run SV-Pop for other models here if needed, that's just the above command with a different model selected.

# Prep window files for visualisation
../SVPop --PREPROCESS --variantFile=Merged
```

After this it's should just be a case of copying the prepped files into the Files/ directory under Visualisation/ and `Rscript easyRun.r`

**Comment by mattravenhall** [comment]
The population detection issue seems to stem from no population file being present during analysis, an example of such a file would be. This file isn't required for a lot of analysis functions, but is required for visualisation.

A sub-populations should be formatted as follows (more info in the [wiki](https://github.com/mattravenhall/SV-Pop/wiki/Analysis-Expanded-Help#additional-arguments))
```tsv
Sample	Country	Region	Continent
sample001_DEL	CountryA	RegionA	ContinentA
sample002_DEL	CountryA	RegionA	ContinentA
sample003_DEL	CountryB	RegionA	ContinentA
sample004_DEL	CountryB	RegionA	ContinentA
sample005_DEL	CountryC	RegionB	ContinentB
sample006_DEL	CountryC	RegionB	ContinentB
sample007_DEL	CountryC	RegionB	ContinentB
sample008_DEL	CountryD	RegionC	ContinentB
```

I've added a check for these population columns in the input files for the visualisation tool, but you'll need to define your sub-populations in such a file in the analysis step for the full pipeline.

For example:
`../SVPop -F=SampleFiles.txt -M=DUP -R=PlasmoDB-46_PvivaxP01.gff -P=subpops.txt
 --threads=20`

**Comment by mattravenhall** [comment]
I've also added an 'Analysis to Visualisation' step through to the wiki examples: https://github.com/mattravenhall/SV-Pop/wiki/Example-Use-Cases#analysis---visualisation-pipeline

**Comment by pietermonsieurs** [comment]
Hi Matt,
Thanks for all the efforts! Indeed, with this updated code, the merged variants and merged windows files are both created. However, it is yet unclear to me how the windows files is created. I have attached the variants and windows files attached (I created an artificial population file with an artificial column "strain" with values "test" and "test2", also attached

[Merged_DUP_chrALL_variants_annotated_v1-2-1.csv.zip](https://github.com/mattravenhall/SV-Pop/files/4960077/Merged_DUP_chrALL_variants_annotated_v1-2-1.csv.zip)
[Merged_DUP_chrALL_windows_annotated_v1-2-1.csv.zip](https://github.com/mattravenhall/SV-Pop/files/4960078/Merged_DUP_chrALL_windows_annotated_v1-2-1.csv.zip)
[pheno2.txt.zip](https://github.com/mattravenhall/SV-Pop/files/4960086/pheno2.txt.zip)
). 


When looking at the variants file, I can see an entry where a duplication is predicted in 5 strains: 
`PvP01_04_v1,698723,732252,33529,5,0.3125,1.0,0.0,"Pv005_sur_delly,Pv020_sur_delly,Pv021_sur_delly,Pv024_sur_delly,Pv025_sur_delly",52,7,0,"1/1,1/1,1/1,1/1,1/1",0,0,5,0,0.0,0.0,,0.0,0.0,1.0,0.0,`

However, when looking at the windows file, all values seems to be zero (extract below). However, I assumed that the windows file is some kind of "helper file" for the visualization of the variations, and should contains more or less the same information as the variants file. 


`PvP01_04_v1,698000,699000,6,"Pv21-19_delly,Pv005_sur_delly,Pv020_sur_delly,Pv021_sur_delly,Pv024_sur_delly,Pv025_sur_delly",0.0,0.0,,
PvP01_04_v1,698500,699500,6,"Pv21-19_delly,Pv005_sur_delly,Pv020_sur_delly,Pv021_sur_delly,Pv024_sur_delly,Pv025_sur_delly",0.0,0.0,,
PvP01_04_v1,699000,700000,6,"Pv21-19_delly,Pv005_sur_delly,Pv020_sur_delly,Pv021_sur_delly,Pv024_sur_delly,Pv025_sur_delly",0.0,0.0,,
PvP01_04_v1,699500,700500,6,"Pv21-19_delly,Pv005_sur_delly,Pv020_sur_delly,Pv021_sur_delly,Pv024_sur_delly,Pv025_sur_delly",0.0,0.0,,
PvP01_04_v1,700000,701000,6,"Pv21-19_delly,Pv005_sur_delly,Pv020_sur_delly,Pv021_sur_delly,Pv024_sur_delly,Pv025_sur_delly",0.0,0.0,,
PvP01_04_v1,700500,701500,6,"Pv21-19_delly,Pv005_sur_delly,Pv020_sur_delly,Pv021_sur_delly,Pv024_sur_delly,Pv025_sur_delly",0.0,0.0,,
PvP01_04_v1,701000,702000,6,"Pv21-19_delly,Pv005_sur_delly,Pv020_sur_delly,Pv021_sur_delly,Pv024_sur_delly,Pv025_sur_delly",0.0,0.0,,
PvP01_04_v1,701500,702500,6,"Pv21-19_delly,Pv005_sur_delly,Pv020_sur_delly,Pv021_sur_delly,Pv024_sur_delly,Pv025_sur_delly",0.0,0.0,,`

Thanks again!

Pieter

**Comment by mattravenhall** [comment]
Your sub-pops file should contain the sample name without the file extension, so rather than:
```
Sample	Strain
Pv004_sur_delly_filter.vcf 	test
Pv005_sur_delly_filter.vcf 	test
Pv017_sur_delly_filter.vcf 	test
Pv019_sur_delly_filter.vcf 	test
Pv020_sur_delly_filter.vcf 	test
Pv021_sur_delly_filter.vcf 	test
Pv022_sur_delly_filter.vcf	test
Pv024_sur_delly_filter.vcf 	test
Pv025_sur_delly_filter.vcf 	test
Pv032_sur_delly_filter.vcf 	test
Pv033_sur_delly_filter.vcf 	test
Pv041_sur_delly_filter.vcf 	test
Pv07-19_delly_filter.vcf 	test2
Pv12-19_delly_filter.vcf 	test2
Pv20-19_delly_filter.vcf 	test2
Pv21-19_delly_filter.vcf 	test2
```

You should have something like:
```
Sample	Strain
Pv004_sur_delly_filter	test
Pv005_sur_delly_filter	test
Pv017_sur_delly_filter	test
Pv019_sur_delly_filter	test
Pv020_sur_delly_filter	test
Pv021_sur_delly_filter	test
Pv022_sur_delly_filter	test
Pv024_sur_delly_filter	test
Pv025_sur_delly_filter	test
Pv032_sur_delly_filter	test
Pv033_sur_delly_filter	test
Pv041_sur_delly_filter	test
Pv07-19_delly_filter	test2
Pv12-19_delly_filter	test2
Pv20-19_delly_filter	test2
Pv21-19_delly_filter	test2
```

You should also check for rogue spaces, as your samples have names like "Pv004_sur_delly_filter.vcf " (ie. there is a trailing space).

**Comment by mattravenhall** [comment]
More info on the variants vs. windows files:

- Variant files contain the specific variants identified.
  - E.g. a deletion in chromosome X from base Y to base Z was found in the listed samples with the displayed quality scores etc.
  - This is useful for identifying specific SVs that are at a high frequency in a specific population, and therefore likely to be under significant selective pressure. (e.g. this kind of approach was used to identify selection for a [specific 436bp duplication of gch1 in Malawian _P. falciparum_](https://malariajournal.biomedcentral.com/articles/10.1186/s12936-016-1634-6))
  - Columns: `| Chromosome | Start | End | Length | Count | Frequency | Quality | Precision | Samples | MapQual | PE | SR | Phase | RefCalls | HetCalls | AltCalls | MisCalls | <Population Counts> | PercRef | PercHet | PercAlt | PercMissing | Feature |`
- Windows files instead consider whether a specific region (default 1kbp windows with a 0.5kbp overlap) contains a specific model of structural variation.
  - E.g. chromosome X from base Y to Z contains a deletion in N samples and sub-populations etc. This is what the visualisation module displays.
  - This is useful for identifying disruption of a specific genomic region at high frequency, and may signal selection for regional disruption by a variety of specific structural variants. (e.g. there are [lots of specific duplications of crt](https://www.nature.com/articles/s41598-019-44599-0), but they all duplicate the same region)
  - Columns: `| Chromosome | Start | End | Count | Samples | <Population Counts> | <Population Fst> | Feature |`

**Comment by pietermonsieurs** [comment]
OK, great thanks for the additional explanation on variants versus windows file. 
Removing the file extension indeed did the trick. Thanks!

**Comment by mattravenhall** [comment]
Happy to help, I'll now close this issue.
